# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Lcc.create(code: 'A', label: 'General works', subclass: false, kmapper_id: 1)
Lcc.create(code: 'AC', label: 'Collections. Series. Collected works', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AE', label: 'Encyclopedias', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AG', label: 'Dictionaries and other general reference works', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AI', label: 'Indexes', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AM', label: 'Museums. Collectors and collecting', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AN', label: 'Newspapers', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AP', label: 'Periodicals', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AS', label: 'Academies and learned societies', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AY', label: 'Yearbooks. Almanacs. Directories', subclass: true, kmapper_id: 1)
Lcc.create(code: 'AZ', label: 'History of scholarship and learning. The humanities', subclass: true, kmapper_id: 2)
Lcc.create(code: 'B', label: 'Philosophy. Psychology. Religion', subclass: false, kmapper_id: 4)
Lcc.create(code: 'B', label: 'Philosophy', subclass: true, kmapper_id: 5)
Lcc.create(code: 'BC', label: 'Logic', subclass: true, kmapper_id: 5)
Lcc.create(code: 'BD', label: 'Speculative philosophy', subclass: true, kmapper_id: 5)
Lcc.create(code: 'BF', label: 'Psychology', subclass: true, kmapper_id: 6)
Lcc.create(code: 'BH', label: 'Aesthetics', subclass: true, kmapper_id: 6)
Lcc.create(code: 'BJ', label: 'Ethics', subclass: true, kmapper_id: 6)
Lcc.create(code: 'BL', label: 'Religions. Mythology. Rationalism', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BM', label: 'Judaism', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BP', label: 'Islam. Bahai Faith. Theosophy, etc.', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BQ', label: 'Buddhism', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BR', label: 'Christianity', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BS', label: 'The Bible', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BT', label: 'Doctrinal Theology', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BV', label: 'Practical Theology', subclass: true, kmapper_id: 7)
Lcc.create(code: 'BX', label: 'Christian Denominations', subclass: true, kmapper_id: 7)
Lcc.create(code: 'C', label: 'Auxiliary sciences of history', subclass: false, kmapper_id: 8)
Lcc.create(code: 'C', label: 'Auxiliary sciences of history', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CB', label: 'History of Civilization', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CC', label: 'Archaeology', subclass: true, kmapper_id: 9)
Lcc.create(code: 'CD', label: 'Diplomatics. Archives. Seals', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CE', label: 'Technical Chronology. Calendar', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CJ', label: 'Numismatics', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CN', label: 'Inscriptions. Epigraphy', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CR', label: 'Heraldry', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CS', label: 'Genealogy', subclass: true, kmapper_id: 8)
Lcc.create(code: 'CT', label: 'Biography', subclass: true, kmapper_id: 8)
Lcc.create(code: 'D', label: 'World history and history of Europe, Asia, Africa, Australia, New Zealand, etc.', subclass: false, kmapper_id: 8)
Lcc.create(code: 'D', label: 'History', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DA', label: 'History of Great Britain', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DAW', label: 'History of Central Europe', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DB', label: 'History of Austria. Liechtenstein. Hungary. Czechoslovakia', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DC', label: 'History of France', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DD', label: 'History of Germany', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DE', label: 'History of the Greco-Roman world', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DF', label: 'History of Greece', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DG', label: 'History of Italy', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DH', label: 'History of Low Countries.  Benelux Countries', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DJ', label: 'History of Netherlands (Holland)', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DJK', label: 'History of Eastern Europe', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DK', label: 'History of Russia. Soviet Union. Former Soviet Republics', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DL', label: 'History of Northern Europe. Scandinavia', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DP', label: 'History of Spain', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DQ', label: 'History of Switzerland', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DR', label: 'History of Balkan Peninsula', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DS', label: 'History of Asia', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DT', label: 'History of Africa', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DU', label: 'History of Oceania (South Seas)', subclass: true, kmapper_id: 8)
Lcc.create(code: 'DX', label: 'History of Romanies', subclass: true, kmapper_id: 8)
Lcc.create(code: 'E', label: 'History of the Americas', subclass: false, kmapper_id: 8)
Lcc.create(code: 'E', label: 'History of America', subclass: true, kmapper_id: 8)
Lcc.create(code: 'E', label: 'History of the United States', subclass: true, kmapper_id: 8)
Lcc.create(code: 'F', label: 'History of the Americas', subclass: false, kmapper_id: 8)
Lcc.create(code: 'F', label: 'United States local history', subclass: true, kmapper_id: 8)
Lcc.create(code: 'G', label: 'Geography. Anthropology. Recreation', subclass: false, kmapper_id: 10)
Lcc.create(code: 'G', label: 'Geography', subclass: true, kmapper_id: 10)
Lcc.create(code: 'GA', label: 'Mathematical geography. Cartography', subclass: true, kmapper_id: 33)
Lcc.create(code: 'GB', label: 'Physical geography', subclass: true, kmapper_id: 33)
Lcc.create(code: 'GC', label: 'Oceanography', subclass: true, kmapper_id: 33)
Lcc.create(code: 'GE', label: 'Environmental sciences', subclass: true, kmapper_id: 33)
Lcc.create(code: 'GF', label: 'Human ecology. Anthropogeography', subclass: true, kmapper_id: 11)
Lcc.create(code: 'GN', label: 'Anthropology', subclass: true, kmapper_id: 11)
Lcc.create(code: 'GR', label: 'Folklore', subclass: true, kmapper_id: 11)
Lcc.create(code: 'GT', label: 'Manners and customs', subclass: true, kmapper_id: 11)
Lcc.create(code: 'GV', label: 'Recreation. Leisure', subclass: true, kmapper_id: 11)
Lcc.create(code: 'H', label: 'Social sciences', subclass: false, kmapper_id: 12)
Lcc.create(code: 'H', label: 'Social sciences', subclass: true, kmapper_id: 12)
Lcc.create(code: 'HA', label: 'Statistics', subclass: true, kmapper_id: 13)
Lcc.create(code: 'HB', label: 'Economic theory. Demography', subclass: true, kmapper_id: 14)
Lcc.create(code: 'HC', label: 'Economic history and conditions', subclass: true, kmapper_id: 14)
Lcc.create(code: 'HD', label: 'Industries. Land use. Labor', subclass: true, kmapper_id: 14)
Lcc.create(code: 'HE', label: 'Transportation and communications', subclass: true, kmapper_id: 36)
Lcc.create(code: 'HF', label: 'Commerce', subclass: true, kmapper_id: 15)
Lcc.create(code: 'HG', label: 'Finance', subclass: true, kmapper_id: 15)
Lcc.create(code: 'HJ', label: 'Public finance', subclass: true, kmapper_id: 15)
Lcc.create(code: 'HM', label: 'Sociology', subclass: true, kmapper_id: 16)
Lcc.create(code: 'HN', label: 'Social history and conditions. Social problems.', subclass: true, kmapper_id: 16)
Lcc.create(code: 'HQ', label: 'The Family. Marriage. Women', subclass: true, kmapper_id: 16)
Lcc.create(code: 'HS', label: 'Societies: secret, benevolent, etc.', subclass: true, kmapper_id: 16)
Lcc.create(code: 'HT', label: 'Communities. Classes. Races', subclass: true, kmapper_id: 16)
Lcc.create(code: 'HV', label: 'Social pathology. Social and public welfare. Criminology', subclass: true, kmapper_id: 16)
Lcc.create(code: 'HX', label: 'Socialism. Communism. Anarchism', subclass: true, kmapper_id: 16)
Lcc.create(code: 'J', label: 'Political science', subclass: false, kmapper_id: 17)
Lcc.create(code: 'J', label: 'General legislative and executive papers', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JA', label: 'Political science', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JC', label: 'Political theory. The state. Theories of the state', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JF', label: 'Political institutions and public administration', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JJ', label: 'Political institutions and public administration (North America)', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JK', label: 'Political institutions and public administration (United States)', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JL', label: 'Political institutions and public administration (Canada, Latin America, etc.)', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JN', label: 'Political institutions and public administration (Europe)', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JQ', label: 'Political institutions and public administration (Asia, Africa, Australia, Pacific Area, etc.)', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JS', label: 'Local government. Municipal government', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JV', label: 'Colonies and colonization. Emigration and immigration. International migration', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JX', label: 'International law', subclass: true, kmapper_id: 17)
Lcc.create(code: 'JZ', label: 'International relations', subclass: true, kmapper_id: 17)
Lcc.create(code: 'K', label: 'Law', subclass: false, kmapper_id: 18)
Lcc.create(code: 'K', label: 'Law in general. Comparative and uniform law. Jurisprudence', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KB', label: 'Religious law in general. Comparative religious law. Jurisprudence', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KBM', label: 'Jewish law. Halakah', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KBP', label: 'Islamic law. Sharī#ah. Fiqh', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KBR', label: 'History of canon law', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KBU', label: 'Law of the Roman Catholic Church. The Holy See', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KD', label: 'Law of the United Kingdom and Ireland', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KDZ', label: 'America. North America', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KE', label: 'Law of Canada', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KF', label: 'Law of the United States', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KG', label: 'Law of Latin America', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KH', label: 'Law of South America', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KJ', label: 'Law of Europe', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KK', label: 'Law of Europe', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KL', label: 'Law of Asia and Eurasia, Africa, Pacific Area, and Antarctica', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KM', label: 'Law of Asia', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KN', label: 'Law of South Asia. Southeast Asia. East Asia', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KP', label: 'Law of South Asia. Southeast Asia. East Asia', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KQ', label: 'Law of Africa', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KR', label: 'Law of Africa', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KS', label: 'Law of Africa', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KT', label: 'Law of Africa', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KU', label: 'Law of Pacific Area', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KV', label: 'Law of Pacific area jurisdictions', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KW', label: 'Law of Pacific area jurisdictions', subclass: true, kmapper_id: 18)
Lcc.create(code: 'KZ', label: 'Law of nations', subclass: true, kmapper_id: 18)
Lcc.create(code: 'L', label: 'Education', subclass: false, kmapper_id: 19)
Lcc.create(code: 'L', label: 'Education', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LA', label: 'History of education', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LB', label: 'Theory and practice of education', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LC', label: 'Special aspects of education', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LD', label: 'Individual institutions', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LE', label: 'Individual institutions', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LF', label: 'Individual institutions', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LG', label: 'Individual institutions', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LH', label: 'College and school magazines and papers', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LJ', label: 'Student fraternities and societies, United States', subclass: true, kmapper_id: 19)
Lcc.create(code: 'LT', label: 'Textbooks', subclass: true, kmapper_id: 19)
Lcc.create(code: 'M', label: 'Music', subclass: false, kmapper_id: 20)
Lcc.create(code: 'M', label: 'Music', subclass: true, kmapper_id: 20)
Lcc.create(code: 'ML', label: 'Literature on music', subclass: true, kmapper_id: 20)
Lcc.create(code: 'MT', label: 'Music - Instruction and study', subclass: true, kmapper_id: 20)
Lcc.create(code: 'N', label: 'Fine arts', subclass: false, kmapper_id: 21)
Lcc.create(code: 'N', label: 'Visual arts', subclass: true, kmapper_id: 21)
Lcc.create(code: 'NA', label: 'Architecture', subclass: true, kmapper_id: 22)
Lcc.create(code: 'NB', label: 'Sculpture', subclass: true, kmapper_id: 21)
Lcc.create(code: 'NC', label: 'Drawing. Design. Illustration', subclass: true, kmapper_id: 21)
Lcc.create(code: 'ND', label: 'Painting', subclass: true, kmapper_id: 21)
Lcc.create(code: 'NE', label: 'Print media', subclass: true, kmapper_id: 21)
Lcc.create(code: 'NK', label: 'Decorative arts', subclass: true, kmapper_id: 21)
Lcc.create(code: 'NX', label: 'Arts in general', subclass: true, kmapper_id: 21)
Lcc.create(code: 'P', label: 'Language and literature', subclass: false, kmapper_id: 23)
Lcc.create(code: 'P', label: 'Philology. Linguistics', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PA', label: 'Classical philology', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PB', label: 'Modern languages. Celtic languages', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PC', label: 'Romance', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PD', label: 'Germanic', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PE', label: 'English', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PF', label: 'West Germanic', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PG', label: 'Slavic. Baltic. Albanian', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PH', label: 'Uralic. Basque', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PJ', label: 'Oriental philology and literature', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PK', label: 'Indo-Iranian philology and literature', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PL', label: 'Languages of Eastern Asia, Africa, Oceania', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PM', label: 'Hyperborean, Indian, and artificial languages', subclass: true, kmapper_id: 24)
Lcc.create(code: 'PN', label: 'Literature', subclass: true, kmapper_id: 25)
Lcc.create(code: 'PQ', label: 'French literature', subclass: true, kmapper_id: 25)
Lcc.create(code: 'PR', label: 'English literature', subclass: true, kmapper_id: 25)
Lcc.create(code: 'PS', label: 'American literature', subclass: true, kmapper_id: 25)
Lcc.create(code: 'PT', label: 'German literature', subclass: true, kmapper_id: 25)
Lcc.create(code: 'PZ', label: 'Fiction and juvenile belles lettres', subclass: true, kmapper_id: 25)
Lcc.create(code: 'Q', label: 'Science', subclass: false, kmapper_id: 26)
Lcc.create(code: 'Q', label: 'Science', subclass: true, kmapper_id: 26)
Lcc.create(code: 'QA', label: 'Mathematics', subclass: true, kmapper_id: 27)
Lcc.create(code: 'QA71', label: 'Instruments and machines', subclass: true, kmapper_id: 28)
Lcc.create(code: 'QA72', label: 'Instruments and machines', subclass: true, kmapper_id: 28)
Lcc.create(code: 'QA73', label: 'Instruments and machines', subclass: true, kmapper_id: 28)
Lcc.create(code: 'QA74', label: 'Instruments and machines', subclass: true, kmapper_id: 28)
Lcc.create(code: 'QA75', label: 'Instruments and machines', subclass: true, kmapper_id: 28)
Lcc.create(code: 'QA76', label: 'Instruments and machines', subclass: true, kmapper_id: 28)
Lcc.create(code: 'QB', label: 'Astronomy', subclass: true, kmapper_id: 29)
Lcc.create(code: 'QC', label: 'Physics', subclass: true, kmapper_id: 30)
Lcc.create(code: 'QD', label: 'Chemistry', subclass: true, kmapper_id: 31)
Lcc.create(code: 'QE', label: 'Geology', subclass: true, kmapper_id: 33)
Lcc.create(code: 'QH', label: 'Natural history', subclass: true, kmapper_id: 32)
Lcc.create(code: 'QK', label: 'Botany', subclass: true, kmapper_id: 32)
Lcc.create(code: 'QL', label: 'Zoology', subclass: true, kmapper_id: 32)
Lcc.create(code: 'QM', label: 'Human anatomy', subclass: true, kmapper_id: 32)
Lcc.create(code: 'QP', label: 'Physiology', subclass: true, kmapper_id: 32)
Lcc.create(code: 'QR', label: 'Microbiology', subclass: true, kmapper_id: 32)
Lcc.create(code: 'R', label: 'Medicine', subclass: false, kmapper_id: 35)
Lcc.create(code: 'R', label: 'Medicine', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RA', label: 'Public aspects of medicine', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RB', label: 'Pathology', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RC', label: 'Internal medicine', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RD', label: 'Surgery', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RE', label: 'Ophthalmology', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RF', label: 'Otorhinolaryngology', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RG', label: 'Gynecology and obstetrics', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RJ', label: 'Pediatrics', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RK', label: 'Dentistry', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RL', label: 'Dermatology', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RM', label: 'Therapeutics. Pharmacology', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RS', label: 'Pharmacy and materia medica', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RT', label: 'Nursing', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RV', label: 'Botanic, Thomsonian, and eclectic medicine', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RX', label: 'Homeopathy', subclass: true, kmapper_id: 35)
Lcc.create(code: 'RZ', label: 'Other systems of medicine', subclass: true, kmapper_id: 35)
Lcc.create(code: 'S', label: 'Agriculture', subclass: false, kmapper_id: 34)
Lcc.create(code: 'S', label: 'Agriculture', subclass: true, kmapper_id: 34)
Lcc.create(code: 'SB', label: 'Plant culture', subclass: true, kmapper_id: 34)
Lcc.create(code: 'SD', label: 'Forestry', subclass: true, kmapper_id: 34)
Lcc.create(code: 'SF', label: 'Animal culture', subclass: true, kmapper_id: 34)
Lcc.create(code: 'SH', label: 'Aquaculture. Fisheries. Angling', subclass: true, kmapper_id: 34)
Lcc.create(code: 'SK', label: 'Hunting sports', subclass: true, kmapper_id: 34)
Lcc.create(code: 'T', label: 'Technology', subclass: false, kmapper_id: 36)
Lcc.create(code: 'T', label: 'Technology', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TA', label: 'Engineering. Civil engineering', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TC', label: 'Hydraulic engineering', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TD', label: 'Environmental technology. Sanitary engineering', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TE', label: 'Highway engineering. Roads and pavements', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TF', label: 'Railroad engineering and operation', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TG', label: 'Bridge engineering', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TH', label: 'Building construction', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TJ', label: 'Mechanical engineering and machinery', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TK', label: 'Electrical engineering. Electronics. Nuclear engineering', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TL', label: 'Motor vehicles. Aeronautics. Astronautics', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TN', label: 'Mining engineering. Metallurgy', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TP', label: 'Chemical technology', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TR', label: 'Photography', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TS', label: 'Manufactures', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TT', label: 'Handicrafts. Arts and crafts', subclass: true, kmapper_id: 36)
Lcc.create(code: 'TX', label: 'Home economics', subclass: true, kmapper_id: 36)
Lcc.create(code: 'U', label: 'Military science', subclass: false, kmapper_id: 37)
Lcc.create(code: 'U', label: 'Military science', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UA', label: 'Armies: Organization, distribution, military situation', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UB', label: 'Military administration', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UC', label: 'Maintenance and transportation', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UD', label: 'Infantry', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UE', label: 'Cavalry. Armor', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UF', label: 'Artillery', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UG', label: 'Military engineering', subclass: true, kmapper_id: 37)
Lcc.create(code: 'UH', label: 'Other military services', subclass: true, kmapper_id: 37)
Lcc.create(code: 'V', label: 'Naval science', subclass: false, kmapper_id: 38)
Lcc.create(code: 'V', label: 'Naval science', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VA', label: 'Navies: Organization, distribution, naval situation', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VB', label: 'Naval administration', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VC', label: 'Naval maintenance', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VD', label: 'Naval seamen', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VE', label: 'Marines', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VF', label: 'Naval ordnance', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VG', label: 'Minor services of navies', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VK', label: 'Navigation. Merchant marine', subclass: true, kmapper_id: 38)
Lcc.create(code: 'VM', label: 'Naval architecture. Shipbuilding. Marine engineering', subclass: true, kmapper_id: 38)
Lcc.create(code: 'Z', label: 'Bibliography. Library science. Information resources', subclass: false, kmapper_id: 3)
Lcc.create(code: 'Z', label: 'Books. Writing. Paleography', subclass: true, kmapper_id: 3)
Lcc.create(code: 'ZA', label: 'Information resources', subclass: true, kmapper_id: 3)
