# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Kmapper.create(label: 'General works', color: '#F9C80E')
Kmapper.create(label: 'Humanities', color: '#F9C80E')
Kmapper.create(label: 'Library science', color: '#F9C80E')
Kmapper.create(label: 'Philosophy and theology', color: '#c200fb')
Kmapper.create(label: 'Philosophy', color: '#c200fb')
Kmapper.create(label: 'Psychology', color: '#c200fb')
Kmapper.create(label: 'Theology', color: '#c200fb')
Kmapper.create(label: 'History', color: '#c200fb')
Kmapper.create(label: 'Archaeology', color: '#F9C80E')
Kmapper.create(label: 'Human geography', color: '#F9C80E')
Kmapper.create(label: 'Anthropology', color: '#F9C80E')
Kmapper.create(label: 'Social sciences', color: '#ec0868')
Kmapper.create(label: 'Statistics', color: '#05b3d2')
Kmapper.create(label: 'Economics', color: '#05b3d2')
Kmapper.create(label: 'Business', color: '#05b3d2')
Kmapper.create(label: 'Sociology', color: '#ec0868')
Kmapper.create(label: 'Political science', color: '#ec0868')
Kmapper.create(label: 'Law', color: '#c200fb')
Kmapper.create(label: 'Education', color: '#ec0868')
Kmapper.create(label: 'Music', color: '#ec0868')
Kmapper.create(label: 'Visual arts', color: '#ec0868')
Kmapper.create(label: 'Architecture', color: '#757575')
Kmapper.create(label: 'Languages and literature', color: '#F9C80E')
Kmapper.create(label: 'Languages', color: '#F9C80E')
Kmapper.create(label: 'Literature', color: '#F9C80E')
Kmapper.create(label: 'Natural science', color: '#03f7eb')
Kmapper.create(label: 'Mathematics', color: '#05b3d2')
Kmapper.create(label: 'Computer science', color: '#757575')
Kmapper.create(label: 'Space sciences', color: '#03f7eb')
Kmapper.create(label: 'Physics', color: '#03f7eb')
Kmapper.create(label: 'Chemistry', color: '#03f7eb')
Kmapper.create(label: 'Biology', color: '#03f7eb')
Kmapper.create(label: 'Earth science', color: '#03f7eb')
Kmapper.create(label: 'Agriculture', color: '#03f7eb')
Kmapper.create(label: 'Medicine and health', color: '#05b3d2')
Kmapper.create(label: 'Engineering and technology', color: '#757575')
Kmapper.create(label: 'Military science', color: '#03f7eb')
Kmapper.create(label: 'Naval science', color: '#05b3d2')